name: Deploy
on:
  push:
    branches:
      - main
env:
  FORCE_COLOR: 2
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify about new deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install --production --frozen-lockfile
      - name: Build static files
        run: npm build
      - name: Check files changes
        id: hash
        run: ./node_modules/.bin/ssdeploy changed
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
      - name: Auth Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
      - name: Install Google Cloud
        if: "!steps.hash.outputs.noChanges"
        uses: google-github-actions/setup-gcloud@v0
      - name: Deploy files
        if: "!steps.hash.outputs.noChanges"
        run: ./node_modules/.bin/ssdeploy deploy --verbose
        env:
          GCLOUD_APP: ${{ secrets.GCLOUD_APP }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ secrets.WEBSITE_URL }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
