name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '>=13.2'
YARN      - name: Get Yarn cache path
YARN        id: yarn-cache
YARN        run: echo "::set-output name=dir::$(yarn cache dir)"
YARN      - name: Cache Yarn
YARN        uses: actions/cache@v1
YARN        with:
YARN          path: ${{ steps.yarn-cache.outputs.dir }}
YARN          key: yarn-production-${{ hashFiles('**/yarn.lock') }}
YARN          restore-keys: yarn-production-
NPM       - name: Cache npm
NPM         uses: actions/cache@v1
NPM         with:
NPM           path: ${{ steps.npm-cache.outputs.dir }}
NPM           key: npm-production-${{ hashFiles('**/package-lock.json') }}
NPM           restore-keys: npm-production-
NPM       - name: Get npm cache path
NPM         id: npm-cache
NPM         run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Install build dependencies
YARN        run: yarn install --production
NPM         run: npm ci --only=production
      - name: Build static files
YARN        run: yarn build
NPM         run: npm build
        env:
          FORCE_COLOR: 2
      - name: Check files changes
        id: hash
        run: npx ssdeploy changed
        env:
          FORCE_COLOR: 2
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
      - name: Install Google Cloud
        if: "!steps.hash.outputs.noChanges"
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '274.0.1'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy files
        if: "!steps.hash.outputs.noChanges"
        run: npx ssdeploy deploy --verbose
        env:
          FORCE_COLOR: 2
          GCLOUD_APP: ${{ secrets.GCLOUD_APP }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
