name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.24.0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - name: Install all dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test
        env:
          FORCE_COLOR: 2
